LearningHubMVC/LearningHubMVC/Controllers/EnrollmentController.cs
using LearningHubMVC.Models;
using LearningHubMVC.ServiceRepository;
using Microsoft.AspNetCore.Mvc;

namespace LearningHubMVC.Controllers
{
    public class EnrollmentController : Controller
    {
        public static List<Enrollment>? myenrollments = new List<Enrollment>();
        public static List<Enrollment>? presentenrollments = new List<Enrollment>();
        public void GetMyEnrollments()
        {
            try
            {

                myenrollments.Clear();
                presentenrollments.Clear();
                if (HttpContext.Session.GetString("token") == null) return;
                string un = HttpContext.Session.GetString("user");
                ServiceRepo serviceObj = new ServiceRepo(HttpContext.Session.GetString("token"), un);             //Enrollments/{un}/myenrollments
                myenrollments = serviceObj.GetMyEnrollments<Enrollment>("Enrollments/"+un+"/myenrollments");////update needed

                foreach (var item in myenrollments)
                {
                    if (item.Course.startdate <= DateTime.Now && item.Course.enddate >= DateTime.Now)
                    {
                        presentenrollments.Add(item);
                    }
                }
                
                ViewBag.presentenrollments = presentenrollments;
                
            }
            catch (Exception)
            {
                throw;
            }
        }
        public List<Enrollment> GetPresentEnrollments()
        {
            GetMyEnrollments();
            return presentenrollments;
        }
        public List<Enrollment> MyEnrollments()
        {
            GetMyEnrollments();
            return myenrollments;
        }
        public IActionResult Enroll(int id)
        {
            if (HttpContext.Session.GetString("token") == null) return Redirect("/Courses/Index");
            string un = HttpContext.Session.GetString("user");
            Enrollment en = new Enrollment();
            en.CourseID = id;
            en.UserID = un;
            en.enrollmentDate = DateTime.Now;
            en.Course = null;
            en.User = null;
            
            
            ServiceRepo serviceObj = new ServiceRepo(HttpContext.Session.GetString("token"), un);
            Course v = serviceObj.GetOneResponse<Course>("Courses/" + id.ToString());
            
            serviceObj.PostResponse("Enrollments", en);
            TempData["toastmsg"] = "Successfully , Enrolled for course '"+v.Name+"'";

            return Redirect("/Courses/Index");
        }
        public IActionResult Disenroll(int id)
        {
            if (HttpContext.Session.GetString("token") == null) return Redirect("/Courses/Index");
            string un = HttpContext.Session.GetString("user");
            ServiceRepo serviceObj = new ServiceRepo(HttpContext.Session.GetString("token"), HttpContext.Session.GetString("user"));
            Enrollment e = serviceObj.GetOneResponse<Enrollment>("Enrollments/" + id.ToString());//it itself contains course no need of below 2 lines
            int cid = e.CourseID;
            Course v = serviceObj.GetOneResponse<Course>("Courses/" + cid.ToString());
            serviceObj.DeleteResponse("Enrollments/" + id.ToString());
            TempData["toastmsg"] = "Course '"+v.Name+"' Disenrolled Successfully!!!";
            return Redirect("/Courses/Index");
        }
            public IActionResult Index()
        {
            return View();
        }
    }
}

LearningHubMVC/LearningHubMVC/Controllers/UserController.cs
using LearningHubMVC.Models;
using LearningHubMVC.ServiceRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Net;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;

namespace LearningHubMVC.Controllers
{
    public class UserController : Controller
    {
        public static List<ShownCourse>? scourses = new List<ShownCourse>();
        public static List<ShownUser>? susers = new List<ShownUser>();
        public static List<ShownCourse>? presentSCourses = new List<ShownCourse>();
        public static List<Enrollment>? myenrollments = new List<Enrollment>();
        public static List<Enrollment>? presentenrollments = new List<Enrollment>();
        public static HashSet<int>? courseId = new HashSet<int>();
        public static Dictionary<int, int>? courseenroll = new Dictionary<int, int>();
        public static List<User> traineranduser = new List<User>();
        private readonly IConfiguration _configuration;
        public UserController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public void Gettrainers()
        {
            try
            {
                if (HttpContext.Session.GetString("token") == null) return;
                if (HttpContext.Session.GetString("role") != "admin") return; 
                string un = HttpContext.Session.GetString("user");
                ServiceRepo serviceObj = new ServiceRepo(HttpContext.Session.GetString("token"), un);
                List<User> users = serviceObj.GetResponse<User>("Users");
                foreach (var item in users)
                {
                    if (item.Role.ToString() == "admin") continue;
                    traineranduser.Add(item);
                }
            }
            catch (Exception Exp)
            {
                String s = Exp.Message;
                throw;
            }
        }
        public IActionResult Index()
        {
            Gettrainers();
            return View(traineranduser);
        }
        public IActionResult LoginPage()
        {
            return View();
        }
        public IActionResult TryLogin(LoginUser user)
        {

            ServiceRepo serviceObj = new ServiceRepo("",user.username);
            string token=serviceObj.GetToken("AccountY",user);
            if(token.Contains("\""))
            {
                int n = token.Length;
                string ns = "";
                for (int i = 1; i < n - 1; i++)
                {
                    ns += token[i];
                    //Console.WriteLine(token[i]);
                }
                token = ns;
            }
            if (token == null)
            {
                TempData["msg"] = token;
                return RedirectToAction("LoginPage");
            }
            if (token.Length == 0)
            {
                TempData["msg"] = token;
                return RedirectToAction("LoginPage");
            }
            HttpContext.Session.SetString("token", token);
            HttpContext.Session.SetString("user", user.username);
            string role = getRole(token);
            HttpContext.Session.SetString("role", role);
            return Redirect("/Courses/Index/");
            //return Redirect("/Courses/GetValues/");
        }
        
        public string getRole(string token)
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            //var key = Encoding.ASCII.GetBytes(_configuration["Jwt:Key"]);
            
            //_configuration is null find it first
            var key = Convert.FromBase64String(_configuration["Jwt:Key"].ToString());
            int j = 10;
            tokenHandler.ValidateToken(token, new TokenValidationParameters
            {
                ValidateIssuerSigningKey = true,
                IssuerSigningKey = new SymmetricSecurityKey(key),
                ValidateIssuer = false,
                ValidateAudience = false,
                //ValidIssuer = _configuration["Jwt:ValidIssuer"],
                //ValidAudience = _configuration["Jwt:ValidAudience"],
                // set clockskew to zero so tokens expire exactly at token expiration time (instead of 5 minutes later)
                //ClockSkew = TimeSpan.Zero
            }, out SecurityToken validatedToken);

            var jwtToken = (JwtSecurityToken)validatedToken;
            //var Id = jwtToken.Claims.FirstOrDefault(x => x.Type == "Id")?.Value;
            //get the user name and role from the JWT token.
            // username = jwtToken.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value;
            
            var role = jwtToken.Claims.FirstOrDefault(x => x.Type == "role")?.Value;
            return role.ToString();
        }
    }
}

LearningHubMVC/LearningHubMVC/Views/Courses/AddCourse.cshtml
@model LearningHubMVC.Models.Course
@{
    ViewBag.Title = "Create Course";
}
<br />
<br />
<div class="row">  
    <div class="col-md-9">  
        <form asp-controller="Courses" asp-action="Create">  
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>  
            @Html.HiddenFor(m=>m.ID) 
            <div class="form-group">  
                <label asp-for="Name" class="control-label"></label>  
                <input asp-for="Name" class="form-control type="text" />  
                <span asp-validation-for="Name" class="text-danger"></span>  
            </div> 
            <br />
            <label>Start Date</label><br/>
            @Html.TextBoxFor(m => m.startdate, "{0:dd/MMM/yyyy hh:mm tt}")
            @Html.ValidationMessageFor(m=>m.startdate)
            <br/>
            <br />
            <label>End Date</label><br/>
            @Html.TextBoxFor(m => m.enddate, "{0:dd/MMM/yyyy hh:mm tt}")
            @Html.ValidationMessageFor(m=>m.enddate)
            <!--
                <div class="form-group">  
                    <label asp-for="startdate" class="control-label"></label>  
                    <input asp-for="startdate" class="form-control"/>  
                    <span asp-validation-for="startdate" class="text-danger"></span>  
                </div>  
                <div class="form-group">  
                    <label asp-for="enddate" class="control-label"></label>  
                    <input asp-for="enddate" class="form-control" />  
                    <span asp-validation-for="enddate" class="text-danger"></span>  
                </div>  
            -->
            <br />
            <br/>
            <div class="form-group">  
                <label asp-for="duration" class="control-label"></label>  
                <input asp-for="duration" class="form-control" type="number"/>  
                <span asp-validation-for="duration" class="text-danger"></span>  
            </div>  
            <br />
            <div class="form-group">  
                <label asp-for="info" class="control-label"></label>  
                <textarea asp-for="info" class="form-control" rows="5"></textarea>
                <span asp-validation-for="info" class="text-danger"></span>  
            </div>
            <br />
            <div class="form-group">  
                        <input type="submit" value="Save Course Details" class="btn btn-primary" />  
            </div>  
        </form>  
            </div>  
        </div>  
  
        <div>  
            <a asp-action="Index">Back to List</a>  
        </div>  
  
        @section Scripts {  
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}  
        }  

LearningHubMVC/LearningHubMVC/Views/Courses/Edit.cshtml
@model LearningHubMVC.Models.Course
@{
    ViewBag.Title = "Update Course";
}
<br />
<br />
<div class="row">  
    <div class="col-md-9">  
        <form asp-controller="Courses" asp-action="Update">  
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>  
            @Html.HiddenFor(m=>m.ID)
            <br/>
            <div class="form-group">  
                <label asp-for="Name" class="control-label"></label>  
                <input asp-for="Name" class="form-control type="text" />  
                <span asp-validation-for="Name" class="text-danger"></span>  
            </div> 
            <br />
            <label>Start Date</label><br/>
            @Html.TextBoxFor(m => m.startdate, "{0:dd/MMM/yyyy hh:mm tt}")
            @Html.ValidationMessageFor(m=>m.startdate)
            <br/>
            <br />
            <label>End Date</label><br/>
            @Html.TextBoxFor(m => m.enddate, "{0:dd/MMM/yyyy hh:mm tt}")
            @Html.ValidationMessageFor(m=>m.enddate)
            <br />
            <!--
                <div class="form-group">  
                    <label asp-for="startdate" class="control-label"></label>  
                    <input asp-for="startdate" class="form-control"/>  
                    <span asp-validation-for="startdate" class="text-danger"></span>  
                </div>  
                <div class="form-group">  
                    <label asp-for="enddate" class="control-label"></label>  
                    <input asp-for="enddate" class="form-control" />  
                    <span asp-validation-for="enddate" class="text-danger"></span>  
                </div>  
            -->
            <br/>
            <div class="form-group">  
                <label asp-for="duration" class="control-label"></label>  
                <input asp-for="duration" class="form-control" type="number"/>  
                <span asp-validation-for="duration" class="text-danger"></span>  
            </div>  
            <br />
            <div class="form-group">  
                <label asp-for="info" class="control-label"></label>  
                <textarea asp-for="info" class="form-control" rows="5"></textarea>
                <span asp-validation-for="info" class="text-danger"></span>  
            </div>
           <br />
            <div class="form-group">  
                        <input type="submit" value="Save Course Details" class="btn btn-primary" />  
            </div>  
        </form>  
            </div>  
        </div>  
  
        <div>  
            <a asp-action="Index">Back to List</a>  
        </div>  
  
        @section Scripts {  
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}  
        } 

LearningHubMVC/LearningHubMVC/Views/Courses/GetValues.cshtml
@model LearningHubMVC.Models.User
@{
    ViewBag.Title = "Get Values";
}
<br />
<br />
<div class="row">  
    <div class="col-md-9">  
        
            
            <div>  
                <label>ID:  </label>  
                <label>@Model.ID </label>  
            </div> 
           <div>  
                <label>Password:  </label>  
                <label>@Model.password </label>               
            </div> 
            <div>  
                <label>Role:  </label>  
                <label>@Model.Role </label>               
            </div> 
            
            <div>  
                <label>Registered Date:  </label>  
                <label>@Model.registeredDate </label>            
            </div> 
        
            
    </div>  
 </div>  
        <div>  
            <a asp-action="LoginPage" asp-controller="User">Back to List</a>  
        </div>  
  

LearningHubMVC/LearningHubMVC/Views/Courses/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@model IEnumerable<LearningHubMVC.Models.ShownCourse>
@{
    ViewBag.Title = "Ongoing Courses";
}


<head>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap5.min.css" rel="stylesheet"></link>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<br/>
@if(@HttpContextAccessor.HttpContext.Session.GetString("role")=="trainer"||
    @HttpContextAccessor.HttpContext.Session.GetString("role")=="admin")
{
    <p>
        <a asp-action="AddCourse1">Add New Course</a>
    </p>
}

<div class="container mb-3 mt-3">
    <table class="table table-striped table-bordered" style="width:100%" id="mydatatable">
        <thead>
            <tr>
                <th>Name</th>
                <th>Duration</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Info</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var course in Model)
            {
                <tr>
                    <td>@course.Name</td>
                    <td>@course.duration</td>
                    <td>@string.Format("{0:dd/MMM/yyyy hh:mm tt}", course.startdate)</td>
                    <td>@string.Format("{0:dd/MMM/yyyy hh:mm tt}", course.startdate)</td>
                    <td>@course.info</td>
                    <td>
                        @if(course.isenrolled==true)
                        {
                            <a asp-controller="Enrollment" asp-action="Disenroll" asp-route-id="@course.enrollemntId">Disenroll</a>
                        }
                        else
                        {
                            <a asp-controller="Enrollment" asp-action="Enroll" asp-route-id="@course.ID">Enroll</a>
                        }
                        
                        @if(@HttpContextAccessor.HttpContext.Session.GetString("role")=="admin" || course.istrainer==true)
                        {
                            <span>|</span>
                            <a asp-action="Edit" asp-route-id="@course.ID">Edit</a>
                        } 
                        @if(@HttpContextAccessor.HttpContext.Session.GetString("role")=="admin" || course.istrainer==true)
                        {
                            <span>|</span>
                            <a asp-action="Delete2" asp-route-id="@course.ID">Delete</a>
                        }
                        
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            
        </tfoot>
    </table> 

    
    
</div>




<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap5.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script>
    $('#mydatatable').DataTable();
</script>